import type { DashboardRecord } from '@/types/domain'

/**
 * Dados de demonstração — mostrados quando `.env` não está configurado (sem
 * VITE_SUPABASE_URL/VITE_SUPABASE_ANON_KEY), pra dar pra ver a interface
 * funcionando sem depender do banco real. Portado 1:1 do DEMO_DATA do
 * dashboard antigo.
 */
export const DEMO_DASHBOARD_ROWS: DashboardRecord[] = [
  {
    colaborador_id: '1',
    nome: 'Ana Souza',
    departamento: 'Fiscal',
    supervisor: 'Marcos',
    status: 'ativo',
    tipo_colaborador: 'efetivo',
    data: '2026-07-15',
    horas_trabalhadas: '08:12:00',
    workmonitor_total: '07:40:00',
    total_gclick: '05:30:00',
    classificacao: 'OK',
    ultima_justificativa: null,
    ultima_justificativa_gestor: null,
    ultima_justificativa_em: null,
    metricas: null,
  },
  {
    colaborador_id: '2',
    nome: 'Bruno Lima',
    departamento: 'Contábil',
    supervisor: 'Marcos',
    status: 'ativo',
    tipo_colaborador: 'efetivo',
    data: '2026-07-15',
    horas_trabalhadas: '06:55:00',
    workmonitor_total: '06:10:00',
    total_gclick: '03:10:00',
    classificacao: 'ABAIXO DO LM',
    ultima_justificativa: 'Consulta médica agendada, já validado com o colaborador.',
    ultima_justificativa_gestor: 'Marcos',
    ultima_justificativa_em: '2026-07-15T18:20:00Z',
    metricas: null,
  },
  {
    colaborador_id: '3',
    nome: 'Carla Mendes',
    departamento: 'Pessoal',
    supervisor: 'Diego',
    status: 'ativo',
    tipo_colaborador: 'efetivo',
    data: '2026-07-15',
    horas_trabalhadas: '10:24:00',
    workmonitor_total: '09:05:00',
    total_gclick: '07:45:00',
    classificacao: 'ACIMA DA JORNADA',
    ultima_justificativa: null,
    ultima_justificativa_gestor: null,
    ultima_justificativa_em: null,
    metricas: null,
  },
  {
    colaborador_id: '4',
    nome: 'Diego Alves',
    departamento: 'Fiscal',
    supervisor: 'Marcos',
    status: 'ativo',
    tipo_colaborador: 'efetivo',
    data: '2026-07-15',
    horas_trabalhadas: null,
    workmonitor_total: null,
    total_gclick: '00:00:00',
    classificacao: 'SEM LANCAMENTO',
    ultima_justificativa: null,
    ultima_justificativa_gestor: null,
    ultima_justificativa_em: null,
    metricas: null,
  },
  {
    colaborador_id: '5',
    nome: 'Elaine Rocha',
    departamento: 'Contábil',
    supervisor: 'Diego',
    status: 'ativo',
    tipo_colaborador: 'estagiario',
    data: '2026-07-15',
    horas_trabalhadas: '06:00:00',
    workmonitor_total: '05:40:00',
    total_gclick: '04:50:00',
    classificacao: 'OK',
    ultima_justificativa: null,
    ultima_justificativa_gestor: null,
    ultima_justificativa_em: null,
    metricas: null,
  },
]
